name: push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: save cache
      uses: actions/cache/save@v4
      with:
        path: |
          poison
        key: poison_key
